Show precise location for config parsing error (#1530)
Finally, we can actually fix #783, big thanks to serde‑saphyr and
@bourumir-wyngs!

For this invalid config:
```yaml
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - name: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
```

Before:

```console
❯ prek validate-config .pre-commit-config.yaml
error: Failed to parse `.pre-commit-config.yaml`
  caused by: Invalid remote repo: missing field `id`
```

After:
```console
❯ ~/code/rust/prek/target/debug/prek validate-config .pre-commit-config.yaml
error: Failed to parse `.pre-commit-config.yaml`
  caused by: error: line 6 column 9: missing field `id` at line 6, column 9
 --> <input>:6:9
  |
4 |     hooks:
5 |       - id: trailing-whitespace
6 |       - name: end-of-file-fixer
  |         ^ missing field `id` at line 6, column 9
7 |       - id: check-yaml
8 |       - id: check-added-large-files
  |
```